version: '3'
services:
    server:
        build:
            context: ./
            dockerfile: server.docker
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./:/var/www
        links:
            - mariadb
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mariadb"
    mariadb:
        image: mariadb:10.3
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=further"
        ports:
            - "33061:3306"
        volumes:
            - mysql_bkp:/var/lib/mysql
    pma:
        image: phpmyadmin/phpmyadmin
        environment:
            - "PMA_USER=root"
            - "PMA_PASSWORD=secret"
        ports:
            - "8001:80"
        links:
            - mariadb:db
volumes:
    mysql_bkp:
