name: PHPUnit

on:
    pull_request:
        branches:
          - master

jobs:
    phpinsights:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: true
          matrix:
            php: [8.0]
            dependency-version: [prefer-stable]

        name: PHP${{ matrix.php }} - ${{ matrix.dependency-version }}

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Cache dependencies
            uses: actions/cache@v1
            with:
              path: ~/.composer/cache/files
              key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

          - name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
              php-version: '8.0'
              extensions: curl, gd, json, mbstring, mysql, xml
              coverage: none

          - name: Install dependencies
            run: composer update --no-interaction --prefer-dist --${{ matrix.dependency-version }}

          - name: Build frontend
            run: npm install && npm run build

          - name: Prepare Laravel Application
            run: |
                cp .env.example .env
                php artisan key:generate

          - name: PHPUnit
            run: vendor/bin/phpunit